name: PR Build and Test
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: wget https://stockfishchess.org/files/stockfish_14.1_linux_x64.zip
      - run: unzip stockfish_14.1_linux_x64.zip
      - run: ln stockfish_14.1_linux_x64/stockfish_14.1_linux_x64 stockfish
      - run: echo $PATH
      - run: export PATH=$PATH:$(pwd)
      - run: go build -v ./...
      - run: go test -v -bench=. ./...
      